repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: flake8
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-executables-have-shebangs
  - id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
