language: python
python:
- 3.6
- 3.7
cache:
  pip: true

install:
- python -m pip install pre-commit setuptools wheel
- python -m pip install -r requirements.txt
- python setup.py install

before_script:
- pre-commit run --all-files
script:
- mkdir html
- sphinx-multiversion docs html
- python setup.py build sdist bdist_wheel
